version: '2'
services:
  db:
    restart: always
    image: postgres:alpine
    volumes:
      - /home/initrax/postgresql:/var/lib/postgresql

  app:
    restart: always
    build: .
    env_file: .env.production
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
      # - redis
    volumes:
      - ./public/assets:/initrax/public/assets
      - ./public/system:/initrax/public/system
      - ./public/packs:/initrax/public/packs
