version: 2
jobs:
  build:
    working_directory: ~/initrax
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: initrax
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: initrax
          POSTGRES_DB: initrax_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      - type: cache-restore
        name: Restore bundle cache
        key: initrax-bundle-{{ checksum "Gemfile.lock" }}

      - type: cache-restore
        name: Restore yarn cache
        key: initrax-bundle-{{ checksum "yarn.lock" }}

      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle

      - run:
          name: Yarn Install
          command: yarn install

      - type: cache-save
        name: Store bundle cache
        key: initrax-bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - type: cache-save
        name: Store yarn cache
        key: initrax-yarn-{{ checksum "yarn.lock" }}
        paths:
          - ~/.yarn-cache

      - run:
          name: Rubocop
          command: bundle exec rubocop

      - run:
          name: ESLint
          command: npm run lint

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace

      - run:
          name: Run Rspec specs
          command: bundle exec rspec

      - run:
          name: Run Javascript specs
          command: npm test

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ];
              then echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts; ssh -p $SSH_PORT $SSH_USER@$SSH_HOST '~/bin/upgrade-initrax -a';
            fi
